| Common Jdl |           |
|------------|-----------|
| 3HAD160    | AACPS3    |
| 3OAR160    | AACPS3    |
| 3OAS160    | AACPS3    |
| 3HAD120    | AACPS7    |
| 3OAR120    | AACPS7    |
| 3OAS120    | AACPS7    |
| ASNS1      | ASNS2     |
| 3HAD120    | FACOAE120 |
| 3OAR120    | FACOAE120 |
| 3OAS120    | FACOAE120 |
| 3HAD160    | FACOAE160 |
| 3OAR160    | FACOAE160 |
| 3OAS160    | FACOAE160 |
| G5SD       | NACODA    |
| GLU5K      | NACODA    |
| GLUDy      | GLUSy     |
| Kabcpp     | Kt2pp     |
| ADK3       | NDPK1     |
| O2tex      | SUCCtex   |
| GRXR       | PAPSR     |
| GTHOr      | PAPSR     |
| PAPSR      | PAPSR2    |
| PIt2rpp    | PIuabcpp  |
| RPI        | TALA      |
| GRXR       | TRDR      |
| GTHOr      | TRDR      |
| PAPSR2     | TRDR      |
| TRPS1      | TRPS3     |
| ZN2tpp     | ZNabcpp   |
| GARFT      | GART      |
| ENO        | O2tex     |
| GAPD       | O2tex     |
| GHMT2r     | PGCD      |
| O2tex      | PGK       |
| O2tex      | PGM       |
| FUM        | PPC       |
| MALS       | PPC       |
| GHMT2r     | PSERT     |
| GHMT2r     | PSP_L     |
| GND        | RPE       |
| RPE        | RPI       |
| RPE        | TKT1      |
| RPI        | TKT1      |
| GND        | TKT2      |
| RPE        | TKT2      |
| RPI        | TKT2      |
| TKT1       | TKT2      |
